import XCTest
@testable import VisionIINA

final class InputConfFormattingTests: XCTestCase {

    func testHeaderConstant() {
        XCTAssertEqual(InputConfFormatting.generatedHeader, "# Generated by IINA\n\n")
    }

    func testFormatRegularLine() {
        let line = InputConfFormatting.formatLine(rawKey: "SPACE", actionTokens: ["cycle", "pause"], isIINACommand: false, comment: nil)
        XCTAssertEqual(line, "SPACE cycle pause")
    }

    func testFormatIINACommandWithComment() {
        let line = InputConfFormatting.formatLine(rawKey: "K", actionTokens: ["toggle-ui"], isIINACommand: true, comment: "show")
        XCTAssertEqual(line, "#@iina K toggle-ui   #show")
    }
}
