import XCTest
@testable import VisionIINA

final class InputConfMappingTests: XCTestCase {

    private func makeTempFile(named name: String, content: String) throws -> String {
        let dir = FileManager.default.temporaryDirectory.appendingPathComponent("vision-iina-tests", isDirectory: true)
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let fileURL = dir.appendingPathComponent(name, isDirectory: false)
        try content.write(to: fileURL, atomically: true, encoding: .utf8)
        return fileURL.path
    }

    func testParseInputConfSkipsCommentsAndBlankLines() throws {
        let path = try makeTempFile(named: "inputconf-1.conf", content: "\n# plain comment\nSPACE cycle pause\n")

        let parsed = try XCTUnwrap(InputConfMapping.parseInputConf(at: path))
        XCTAssertEqual(parsed.count, 1)
        XCTAssertEqual(parsed[0].rawKey, "SPACE")
        XCTAssertEqual(parsed[0].rawAction, "cycle pause")
        XCTAssertFalse(parsed[0].isIINACommand)
    }

    func testParseInputConfParsesIINAExtendedSyntaxAndComment() throws {
        let path = try makeTempFile(named: "inputconf-2.conf", content: "#@iina K toggle-ui   #show ui\n")

        let parsed = try XCTUnwrap(InputConfMapping.parseInputConf(at: path))
        XCTAssertEqual(parsed.count, 1)
        XCTAssertEqual(parsed[0].rawKey, "K")
        XCTAssertEqual(parsed[0].rawAction, "toggle-ui")
        XCTAssertTrue(parsed[0].isIINACommand)
        XCTAssertEqual(parsed[0].comment, "show ui")
    }

    func testSectionExtraction() {
        let mapping = InputConfMapping(rawKey: "A", rawAction: "{my_section} af toggle")
        XCTAssertEqual(mapping.section, "my_section")
    }

    func testGenerateInputConf() {
        let mappings = [
            InputConfMapping(rawKey: "SPACE", rawAction: "cycle pause"),
            InputConfMapping(rawKey: "K", rawAction: "toggle-ui", isIINACommand: true, comment: "show")
        ]

        let text = InputConfMapping.generateInputConf(from: mappings)
        XCTAssertTrue(text.contains("# Generated by IINA"))
        XCTAssertTrue(text.contains("SPACE cycle pause"))
        XCTAssertTrue(text.contains("#@iina K toggle-ui   #show"))
    }

    func testParseInputConfReturnsNilForMissingFile() {
        XCTAssertNil(InputConfMapping.parseInputConf(at: "/tmp/vision-iina-does-not-exist.conf"))
    }
}
