import Foundation

enum InputConfFormatting {
  static let generatedHeader = "# Generated by IINA\n\n"

  static func formatLine(
    rawKey: String,
    actionTokens: [String],
    isIINACommand: Bool,
    comment: String?
  ) -> String {
    let commandPrefix = isIINACommand ? "#@iina " : ""
    let action = actionTokens.joined(separator: " ")
    let commentSuffix = InputConfCommentSuffix.format(comment)
    return "\(commandPrefix)\(rawKey) \(action)\(commentSuffix)"
  }
}
